# Generated by Django 2.1.2 on 2018-10-16 04:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ch', models.CharField(max_length=50, null=True)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('alias_ch', models.CharField(max_length=50, null=True)),
                ('alias_en', models.CharField(max_length=50, null=True)),
                ('iata', models.CharField(max_length=2, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('icao', models.CharField(max_length=3, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('email', models.EmailField(max_length=254, null=True)),
                ('addr', models.TextField(null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('nationality', models.CharField(max_length=2, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
            options={
                'db_table': 'airlines',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ch', models.CharField(max_length=50, null=True)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('iata', models.CharField(max_length=3, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('icao', models.CharField(max_length=4, null=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('nationality', models.CharField(max_length=2, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
            options={
                'db_table': 'airports',
            },
        ),
        migrations.CreateModel(
            name='AirportWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_iata', models.CharField(max_length=4, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('station_pos_lat', models.FloatField()),
                ('station_pos_lon', models.FloatField()),
                ('observe_time', models.DateTimeField()),
                ('metar_text', models.TextField(null=True)),
                ('metar_time', models.DateTimeField()),
                ('wind_dir', models.IntegerField()),
                ('wind_speed', models.IntegerField()),
                ('visibility', models.IntegerField()),
                ('ceiling', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('desc_ch', models.CharField(max_length=50, null=True)),
                ('desc_en', models.CharField(max_length=50, null=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_history', to='airports.Airport')),
            ],
            options={
                'db_table': 'airport_weather',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_date', models.DateTimeField()),
                ('flight_no', models.CharField(max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('is_cargo', models.BooleanField()),
                ('is_outgoing', models.BooleanField()),
                ('sched_time', models.DateTimeField()),
                ('actual_time', models.DateTimeField(null=True)),
                ('est_time', models.DateTimeField(null=True)),
                ('terminal', models.CharField(max_length=10, null=True)),
                ('gate', models.CharField(max_length=10, null=True)),
                ('ac_type', models.CharField(max_length=20, null=True)),
                ('baggage_claim', models.CharField(max_length=20, null=True)),
                ('check_counter', models.CharField(max_length=20, null=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='airports.Airline')),
                ('airport_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departureflights', to='airports.Airport')),
                ('airport_dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivalflights', to='airports.Airport')),
            ],
            options={
                'db_table': 'flights',
            },
        ),
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together={('flight_no', 'flight_date', 'airline')},
        ),
    ]
