# Generated by Django 2.1.2 on 2018-10-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='actual_time',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='est_time',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='gate',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='is_outgoing',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='sched_time',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='terminal',
        ),
        migrations.AddField(
            model_name='flight',
            name='actual_arr_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='actual_dept_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='arr_gate',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='arr_remark',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='arr_terminal',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='dept_gate',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='dept_remark',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='dept_terminal',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='est_arr_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='est_dept_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='route_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='sched_arr_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='sched_dept_time',
            field=models.DateTimeField(null=True),
        ),
    ]
