# Generated by Django 2.1.2 on 2018-10-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0002_auto_20181016_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_date',
            field=models.DateField(),
        ),
    ]
